name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.8.8"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run basic Rails command
        run: bin/rails --version
